-- StudyMatch (Oracle) - FULL (single file)
-- Generated by concatenating the scripts in database/oracle/
-- Run in Oracle SQL Developer using: Run Script (F5)

SET DEFINE OFF;

PROMPT ===== StudyMatch Oracle Full Install =====


PROMPT ===== Running 00_drop_all.sql =====

-- StudyMatch (Oracle) - Drop all objects safely
-- Run this if you want a fresh re-import.

-- ===== Views =====
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_STUDENT_SCORES_SUMMARY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_UNIVERSITY_MAJOR_INFO'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_STUDENT_RECOMMENDED_MAJORS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_TEACHER_ASSIGNMENTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_ADMISSION_STATISTICS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_DIEM_TRUNG_BINH'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_NGANH_PHU_HOP'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_TUYEN_SINH_THEO_NAM'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_GIAO_VIEN_INFO'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_KET_QUA_CHI_TIET'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
-- ===== Procedures =====
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE P_TINH_DIEM_TRUNG_BINH'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE P_DE_XUAT_NGANH'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE P_CAP_NHAT_KET_QUA'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE P_THONG_KE_HOC_SINH'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE P_XOA_DU_LIEU_CU'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE SP_REGISTER_STUDENT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE SP_ADD_STUDENT_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE SP_GET_STUDENT_RECOMMENDATIONS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE SP_UPDATE_MAJOR_INFO'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE SP_GET_UNIVERSITY_STATS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
-- ===== Functions =====
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION F_KT_DA_DANG_KY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION F_TINH_TI_LE_PHU_HOP'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION F_XEP_HANG_NGANH'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION F_DEM_DANH_GIA'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION F_DANH_GIA_TRUNG_BINH'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION F_KT_DIEM_HOP_LE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION F_MO_TA_MUC_DO_PHU_HOP'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_CALCULATE_WEIGHTED_SCORE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_CHECK_STUDENT_ELIGIBILITY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_GET_STUDENT_BLOCK_SCORES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_COUNT_ELIGIBLE_MAJORS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_FORMAT_MAJOR_NAME'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_DAYS_UNTIL_EXAM'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_CALCULATE_AVERAGE_RATING'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
-- ===== Triggers =====
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_DIEM_REFRESH_KETQUA'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_DIEM_VALIDATE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_DANHGIA_VALIDATE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_NGANH_UPDATE_NGAYSUA'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_DIEM_HISTORY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_USERTHI_BI'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_KHOITHI_BI'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_MONTRONGKHOI_BI'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_MONHOC_BI'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_DIEM_BI'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_TRUONGDH_BI'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_NGANH_BI'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_GIAOVIEN_BI'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_TTTS_BI'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_DANHGIA_BI'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_HINHANHGV_BI'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_KETQUA_BI'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
-- ===== Sequences =====
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USERID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_KHOIID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MONID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MONHOCID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DIEMID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TRUONGID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_NGANHID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_GIAOVIENID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TTUYENID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DANHGIAID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HINHANHID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_KETQUAID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LICHSUID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
-- ===== Tables (drop children first) =====
BEGIN EXECUTE IMMEDIATE 'DROP TABLE KETQUADUDOAN CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HINHANHGIAOVIEN CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DANHGIA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE THONGTINTUYENSINH CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE LICH_SU_DIEM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE NGANH CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TRUONGDH CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIEM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MONTRONGKHOITHI CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE KHOITHI CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USERTHI CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE GIAOVIEN CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MONHOC CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
PROMPT Drop done.



PROMPT ===== Running 01_schema.sql =====

-- StudyMatch (Oracle) - Schema + Sequences + Indexes + Constraints
-- Recommended Oracle 12c+.

-- ===== Tables =====

CREATE TABLE UserThi (
    UserId       NUMBER(10) PRIMARY KEY,
    UserName     VARCHAR2(100) NOT NULL,
    MatKhau      VARCHAR2(255) NOT NULL,
    HoTen        VARCHAR2(150) NOT NULL,
    Email        VARCHAR2(100),
    LoaiUser     VARCHAR2(50) DEFAULT 'Student',
    NgayTao      TIMESTAMP DEFAULT SYSTIMESTAMP,
    NgayCapNhat  TIMESTAMP
);

ALTER TABLE UserThi ADD CONSTRAINT uq_userthi_username UNIQUE (UserName);
ALTER TABLE UserThi ADD CONSTRAINT uq_userthi_email UNIQUE (Email);

CREATE TABLE KhoiThi (
    KhoiID   NUMBER(10) PRIMARY KEY,
    TenKhoi  VARCHAR2(50) NOT NULL,
    MoTa     VARCHAR2(500)
);

ALTER TABLE KhoiThi ADD CONSTRAINT uq_khoithi_tenkhoi UNIQUE (TenKhoi);

CREATE TABLE MonTrongKhoiThi (
    MonID   NUMBER(10) PRIMARY KEY,
    KhoiID  NUMBER(10) NOT NULL,
    TenMon  VARCHAR2(100) NOT NULL,
    MaMon   VARCHAR2(20),
    HeSo    NUMBER(3,1) DEFAULT 1.0
);

ALTER TABLE MonTrongKhoiThi
  ADD CONSTRAINT fk_montrongkhoi_khoithi FOREIGN KEY (KhoiID) REFERENCES KhoiThi(KhoiID);
ALTER TABLE MonTrongKhoiThi ADD CONSTRAINT uq_montrongkhoi_mamon UNIQUE (MaMon);
ALTER TABLE MonTrongKhoiThi ADD CONSTRAINT ck_montrongkhoi_heso CHECK (HeSo > 0);

CREATE TABLE MonHoc (
    MonHocID  NUMBER(10) PRIMARY KEY,
    TenMonHoc VARCHAR2(100) NOT NULL,
    MaMonHoc  VARCHAR2(20),
    MoTa      VARCHAR2(500)
);

ALTER TABLE MonHoc ADD CONSTRAINT uq_monhoc_mamonhoc UNIQUE (MaMonHoc);

CREATE TABLE TruongDH (
    TruongID    NUMBER(10) PRIMARY KEY,
    TenTruong   VARCHAR2(200) NOT NULL,
    MaTruong    VARCHAR2(50),
    Website     VARCHAR2(200),
    DiaChi      VARCHAR2(300),
    SoDienThoai VARCHAR2(20),
    Email       VARCHAR2(100)
);

ALTER TABLE TruongDH ADD CONSTRAINT uq_truongdh_matruong UNIQUE (MaTruong);

CREATE TABLE Nganh (
    NganhID        NUMBER(10) PRIMARY KEY,
    TruongID       NUMBER(10) NOT NULL,
    TenNganh       VARCHAR2(200) NOT NULL,
    MaNganh        VARCHAR2(50),
    MoTa           VARCHAR2(1000),
    ChiTieuTuyen   NUMBER(10),
    DiemChuan      NUMBER(5,2),
    KhoiThi_YeuCau VARCHAR2(50),
    NgaySua        TIMESTAMP
);

ALTER TABLE Nganh
  ADD CONSTRAINT fk_nganh_truongdh FOREIGN KEY (TruongID) REFERENCES TruongDH(TruongID);
ALTER TABLE Nganh
  ADD CONSTRAINT ck_nganh_diemchuan CHECK (DiemChuan IS NULL OR (DiemChuan BETWEEN 0 AND 30));

CREATE TABLE GiaoVien (
    GiaoVienID  NUMBER(10) PRIMARY KEY,
    TenGiaoVien VARCHAR2(150) NOT NULL,
    MonDay      VARCHAR2(100),
    Email       VARCHAR2(100),
    SoDienThoai VARCHAR2(20),
    ChuyenMon   VARCHAR2(200)
);

CREATE TABLE ThongTinTuyenSinh (
    ThongTinID   NUMBER(10) PRIMARY KEY,
    NganhID      NUMBER(10) NOT NULL,
    GiaoVienID   NUMBER(10),
    TenHinhThuc  VARCHAR2(100),
    NamTuyen     NUMBER(10),
    DiemChuan    NUMBER(5,2),
    DuToanChiTieu NUMBER(10)
);

ALTER TABLE ThongTinTuyenSinh
  ADD CONSTRAINT fk_ttts_nganh FOREIGN KEY (NganhID) REFERENCES Nganh(NganhID);
ALTER TABLE ThongTinTuyenSinh
  ADD CONSTRAINT fk_ttts_giaovien FOREIGN KEY (GiaoVienID) REFERENCES GiaoVien(GiaoVienID);

CREATE TABLE DanhGia (
    DanhGiaID   NUMBER(10) PRIMARY KEY,
    NganhID     NUMBER(10) NOT NULL,
    UserId      NUMBER(10) NOT NULL,
    DiemDanhGia NUMBER(10),
    NhanXet     VARCHAR2(500),
    NgayDanhGia TIMESTAMP DEFAULT SYSTIMESTAMP
);

ALTER TABLE DanhGia
  ADD CONSTRAINT fk_danhgia_nganh FOREIGN KEY (NganhID) REFERENCES Nganh(NganhID);
ALTER TABLE DanhGia
  ADD CONSTRAINT fk_danhgia_userthi FOREIGN KEY (UserId) REFERENCES UserThi(UserId);
ALTER TABLE DanhGia
  ADD CONSTRAINT ck_danhgia_diem CHECK (DiemDanhGia BETWEEN 1 AND 5);

CREATE TABLE HinhAnhGiaoVien (
    HinhAnhID  NUMBER(10) PRIMARY KEY,
    GiaoVienID NUMBER(10) NOT NULL,
    DuongDan   VARCHAR2(300) NOT NULL,
    MoTa       VARCHAR2(500)
);

ALTER TABLE HinhAnhGiaoVien
  ADD CONSTRAINT fk_hinhanh_gv FOREIGN KEY (GiaoVienID) REFERENCES GiaoVien(GiaoVienID);

CREATE TABLE Diem (
    DiemID     NUMBER(10) PRIMARY KEY,
    UserId     NUMBER(10) NOT NULL,
    MonID      NUMBER(10) NOT NULL,
    DiemThi    NUMBER(4,2) NOT NULL,
    DiemThuong NUMBER(4,2) DEFAULT 0,
    HeSo       NUMBER(3,1) DEFAULT 1.0,
    NgayNhap   TIMESTAMP DEFAULT SYSTIMESTAMP
);

ALTER TABLE Diem
  ADD CONSTRAINT fk_diem_userthi FOREIGN KEY (UserId) REFERENCES UserThi(UserId);
ALTER TABLE Diem
  ADD CONSTRAINT fk_diem_montrongkhoi FOREIGN KEY (MonID) REFERENCES MonTrongKhoiThi(MonID);
ALTER TABLE Diem
  ADD CONSTRAINT ck_diem_thi CHECK (DiemThi BETWEEN 0 AND 10);
ALTER TABLE Diem
  ADD CONSTRAINT ck_diem_thuong CHECK (DiemThuong BETWEEN 0 AND 1);
ALTER TABLE Diem
  ADD CONSTRAINT ck_diem_heso CHECK (HeSo > 0);

CREATE TABLE KetQuaDuDoan (
    KetQuaID     NUMBER(10) PRIMARY KEY,
    UserId       NUMBER(10) NOT NULL,
    NganhID      NUMBER(10) NOT NULL,
    DiemTrungBinh NUMBER(5,2),
    TiLePhuHop   NUMBER(5,2),
    NgayTinhToan TIMESTAMP DEFAULT SYSTIMESTAMP
);

ALTER TABLE KetQuaDuDoan
  ADD CONSTRAINT fk_ketqua_userthi FOREIGN KEY (UserId) REFERENCES UserThi(UserId);
ALTER TABLE KetQuaDuDoan
  ADD CONSTRAINT fk_ketqua_nganh FOREIGN KEY (NganhID) REFERENCES Nganh(NganhID);
ALTER TABLE KetQuaDuDoan
  ADD CONSTRAINT ck_ketqua_tile CHECK (TiLePhuHop BETWEEN 0 AND 100);

-- Optional history/audit table used by triggers
CREATE TABLE Lich_Su_Diem (
    LichSuID    NUMBER(10) PRIMARY KEY,
    DiemID      NUMBER(10) NOT NULL,
    UserId      NUMBER(10) NOT NULL,
    DiemCu      NUMBER(4,2),
    DiemMoi     NUMBER(4,2),
    NgayThayDoi TIMESTAMP DEFAULT SYSTIMESTAMP
);

ALTER TABLE Lich_Su_Diem
  ADD CONSTRAINT fk_lichsu_diem FOREIGN KEY (DiemID) REFERENCES Diem(DiemID);

-- ===== Sequences =====
CREATE SEQUENCE seq_userid START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_khoiid START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_monid START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_monhocid START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_diemid START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_truongid START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_nganhid START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_giaovienid START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_ttuyenid START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_danhgiaid START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_hinhanhid START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_ketquaid START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_lichsuid START WITH 1 INCREMENT BY 1;

-- ===== Indexes =====
CREATE INDEX idx_diem_userid ON Diem(UserId);
CREATE INDEX idx_diem_monid ON Diem(MonID);
CREATE INDEX idx_montrongkhoi_khoiid ON MonTrongKhoiThi(KhoiID);
CREATE INDEX idx_nganh_truongid ON Nganh(TruongID);
CREATE INDEX idx_danhgia_userid ON DanhGia(UserId);
CREATE INDEX idx_danhgia_nganhid ON DanhGia(NganhID);
CREATE INDEX idx_ketqua_userid ON KetQuaDuDoan(UserId);
CREATE INDEX idx_ketqua_nganhid ON KetQuaDuDoan(NganhID);

PROMPT Schema created.



PROMPT ===== Running 02_functions.sql =====

-- StudyMatch (Oracle) - Functions (PL/SQL)

-- ===== Functions from database/functions.sql =====

CREATE OR REPLACE FUNCTION F_KT_DA_DANG_KY (
    p_userid IN NUMBER
)
RETURN BOOLEAN
IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM Diem
    WHERE UserId = p_userid;

    RETURN (v_count > 0);
END F_KT_DA_DANG_KY;
/

CREATE OR REPLACE FUNCTION F_TINH_TI_LE_PHU_HOP (
    p_diem_hoc_sinh IN NUMBER,
    p_diem_chuan_nganh IN NUMBER
)
RETURN NUMBER
IS
    v_ti_le NUMBER;
BEGIN
    IF p_diem_chuan_nganh IS NULL OR p_diem_chuan_nganh = 0 THEN
        v_ti_le := 0;
    ELSE
        v_ti_le := ROUND((NVL(p_diem_hoc_sinh, 0) / p_diem_chuan_nganh) * 100, 2);
        IF v_ti_le > 100 THEN
            v_ti_le := 100;
        ELSIF v_ti_le < 0 THEN
            v_ti_le := 0;
        END IF;
    END IF;

    RETURN v_ti_le;
END F_TINH_TI_LE_PHU_HOP;
/

CREATE OR REPLACE FUNCTION F_XEP_HANG_NGANH (
    p_nganhid IN NUMBER
)
RETURN NUMBER
IS
    v_rank NUMBER;
BEGIN
    SELECT COUNT(*) + 1
      INTO v_rank
      FROM Nganh n1
     WHERE n1.DiemChuan > (SELECT DiemChuan FROM Nganh WHERE NganhID = p_nganhid)
       AND n1.TruongID  = (SELECT TruongID  FROM Nganh WHERE NganhID = p_nganhid);

    RETURN v_rank;
END F_XEP_HANG_NGANH;
/

CREATE OR REPLACE FUNCTION F_DEM_DANH_GIA (
    p_nganhid IN NUMBER
)
RETURN NUMBER
IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM DanhGia
    WHERE NganhID = p_nganhid;

    RETURN NVL(v_count, 0);
END F_DEM_DANH_GIA;
/

CREATE OR REPLACE FUNCTION F_DANH_GIA_TRUNG_BINH (
    p_nganhid IN NUMBER
)
RETURN NUMBER
IS
    v_avg NUMBER;
BEGIN
    SELECT ROUND(AVG(DiemDanhGia), 2) INTO v_avg
    FROM DanhGia
    WHERE NganhID = p_nganhid;

    RETURN NVL(v_avg, 0);
END F_DANH_GIA_TRUNG_BINH;
/

CREATE OR REPLACE FUNCTION F_KT_DIEM_HOP_LE (
    p_diem IN NUMBER
)
RETURN BOOLEAN
IS
BEGIN
    RETURN (p_diem >= 0 AND p_diem <= 10);
END F_KT_DIEM_HOP_LE;
/

CREATE OR REPLACE FUNCTION F_MO_TA_MUC_DO_PHU_HOP (
    p_ti_le IN NUMBER
)
RETURN VARCHAR2
IS
    v_mo_ta VARCHAR2(50);
BEGIN
    CASE
        WHEN p_ti_le >= 90 THEN v_mo_ta := 'Rất Phù Hợp';
        WHEN p_ti_le >= 80 THEN v_mo_ta := 'Phù Hợp';
        WHEN p_ti_le >= 70 THEN v_mo_ta := 'Khá Phù Hợp';
        WHEN p_ti_le >= 60 THEN v_mo_ta := 'Bình Thường';
        ELSE v_mo_ta := 'Ít Phù Hợp';
    END CASE;

    RETURN v_mo_ta;
END F_MO_TA_MUC_DO_PHU_HOP;
/

-- ===== Functions ported from database/functions_sqlserver.sql =====

CREATE OR REPLACE FUNCTION FN_CALCULATE_WEIGHTED_SCORE(
    p_diemthi    IN NUMBER,
    p_diemthuong IN NUMBER,
    p_heso       IN NUMBER
)
RETURN NUMBER
IS
BEGIN
    RETURN NVL(p_diemthi, 0) * NVL(p_heso, 1) + NVL(p_diemthuong, 0);
END FN_CALCULATE_WEIGHTED_SCORE;
/

CREATE OR REPLACE FUNCTION FN_CHECK_STUDENT_ELIGIBILITY(
    p_userid  IN NUMBER,
    p_nganhid IN NUMBER
)
RETURN NUMBER
IS
    v_diemchuan NUMBER;
    v_khoiyeucau VARCHAR2(50);
    v_diemcaonhat NUMBER;
BEGIN
    SELECT DiemChuan, KhoiThi_YeuCau
      INTO v_diemchuan, v_khoiyeucau
      FROM Nganh
     WHERE NganhID = p_nganhid;

    SELECT MAX(d.DiemThi * d.HeSo)
      INTO v_diemcaonhat
      FROM Diem d
      JOIN MonTrongKhoiThi m ON d.MonID = m.MonID
      JOIN KhoiThi k ON m.KhoiID = k.KhoiID
     WHERE d.UserId = p_userid
       AND k.TenKhoi = v_khoiyeucau;

    IF NVL(v_diemcaonhat, 0) >= NVL(v_diemchuan, 0) THEN
        RETURN 1;
    END IF;

    RETURN 0;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END FN_CHECK_STUDENT_ELIGIBILITY;
/

CREATE OR REPLACE FUNCTION FN_GET_STUDENT_BLOCK_SCORES(
    p_userid IN NUMBER,
    p_khoiid IN NUMBER
)
RETURN NUMBER
IS
    v_total NUMBER;
BEGIN
    SELECT NVL(SUM(d.DiemThi * d.HeSo) / NULLIF(COUNT(d.DiemID), 0), 0)
      INTO v_total
      FROM Diem d
      JOIN MonTrongKhoiThi m ON d.MonID = m.MonID
     WHERE d.UserId = p_userid
       AND m.KhoiID = p_khoiid;

    RETURN NVL(v_total, 0);
END FN_GET_STUDENT_BLOCK_SCORES;
/

CREATE OR REPLACE FUNCTION FN_COUNT_ELIGIBLE_MAJORS(
    p_userid IN NUMBER
)
RETURN NUMBER
IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(DISTINCT n.NganhID)
      INTO v_count
      FROM Nganh n
      JOIN Diem d ON d.UserId = p_userid
      JOIN MonTrongKhoiThi m ON d.MonID = m.MonID
      JOIN KhoiThi k ON m.KhoiID = k.KhoiID
     WHERE k.TenKhoi = n.KhoiThi_YeuCau
       AND (d.DiemThi * d.HeSo) >= NVL(n.DiemChuan, 0);

    RETURN NVL(v_count, 0);
END FN_COUNT_ELIGIBLE_MAJORS;
/

CREATE OR REPLACE FUNCTION FN_FORMAT_MAJOR_NAME(
    p_tennganh  IN VARCHAR2,
    p_tentruong IN VARCHAR2
)
RETURN VARCHAR2
IS
BEGIN
    RETURN p_tennganh || ' - ' || p_tentruong;
END FN_FORMAT_MAJOR_NAME;
/

CREATE OR REPLACE FUNCTION FN_DAYS_UNTIL_EXAM(
    p_examdate IN DATE
)
RETURN NUMBER
IS
BEGIN
    RETURN TRUNC(p_examdate) - TRUNC(SYSDATE);
END FN_DAYS_UNTIL_EXAM;
/

CREATE OR REPLACE FUNCTION FN_CALCULATE_AVERAGE_RATING(
    p_nganhid IN NUMBER
)
RETURN NUMBER
IS
    v_avg NUMBER;
BEGIN
    SELECT AVG(DiemDanhGia) INTO v_avg
      FROM DanhGia
     WHERE NganhID = p_nganhid;

    RETURN NVL(ROUND(v_avg, 2), 0);
END FN_CALCULATE_AVERAGE_RATING;
/

PROMPT Functions created.



PROMPT ===== Running 03_procedures.sql =====

-- StudyMatch (Oracle) - Procedures (PL/SQL)

-- ===== Procedures from database/procedures.sql (fixed for Oracle) =====

CREATE OR REPLACE PROCEDURE P_TINH_DIEM_TRUNG_BINH (
    p_userid IN NUMBER,
    p_diem_tb OUT NUMBER
)
IS
BEGIN
    SELECT ROUND(AVG(DiemThi), 2)
      INTO p_diem_tb
      FROM Diem
     WHERE UserId = p_userid;

    p_diem_tb := NVL(p_diem_tb, 0);
END P_TINH_DIEM_TRUNG_BINH;
/

CREATE OR REPLACE PROCEDURE P_DE_XUAT_NGANH (
    p_userid IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
)
IS
    v_diem_tb NUMBER;
BEGIN
    SELECT ROUND(AVG(d.DiemThi), 2)
      INTO v_diem_tb
      FROM Diem d
     WHERE d.UserId = p_userid;

    v_diem_tb := NVL(v_diem_tb, 0);

    OPEN p_cursor FOR
        SELECT
            n.NganhID,
            n.TenNganh,
            t.TenTruong,
            n.DiemChuan,
            ROUND((v_diem_tb / DECODE(n.DiemChuan, 0, 1, n.DiemChuan)) * 100, 2) AS TiLePhuHop,
            n.KhoiThi_YeuCau,
            n.ChiTieuTuyen
        FROM Nganh n
        LEFT JOIN TruongDH t ON n.TruongID = t.TruongID
        WHERE n.DiemChuan IS NOT NULL
          AND (v_diem_tb / DECODE(n.DiemChuan, 0, 1, n.DiemChuan)) * 100 >= 50
        ORDER BY TiLePhuHop DESC;
END P_DE_XUAT_NGANH;
/

CREATE OR REPLACE PROCEDURE P_CAP_NHAT_KET_QUA (
    p_userid IN NUMBER
)
IS
    v_diem_tb NUMBER;
BEGIN
    SELECT ROUND(AVG(DiemThi), 2)
      INTO v_diem_tb
      FROM Diem
     WHERE UserId = p_userid;

    v_diem_tb := NVL(v_diem_tb, 0);

    DELETE FROM KetQuaDuDoan WHERE UserId = p_userid;

    INSERT INTO KetQuaDuDoan (KetQuaID, UserId, NganhID, DiemTrungBinh, TiLePhuHop, NgayTinhToan)
    SELECT
        seq_ketquaid.NEXTVAL,
        p_userid,
        n.NganhID,
        v_diem_tb,
        ROUND((v_diem_tb / DECODE(n.DiemChuan, 0, 1, n.DiemChuan)) * 100, 2),
        SYSTIMESTAMP
    FROM Nganh n
    WHERE n.DiemChuan IS NOT NULL
      AND n.DiemChuan > 0;
END P_CAP_NHAT_KET_QUA;
/

CREATE OR REPLACE PROCEDURE P_THONG_KE_HOC_SINH (
    p_userid IN NUMBER,
    p_so_mon OUT NUMBER,
    p_diem_tb OUT NUMBER,
    p_diem_cao OUT NUMBER,
    p_diem_thap OUT NUMBER
)
IS
BEGIN
    SELECT
        COUNT(*),
        ROUND(AVG(DiemThi), 2),
        MAX(DiemThi),
        MIN(DiemThi)
      INTO p_so_mon, p_diem_tb, p_diem_cao, p_diem_thap
      FROM Diem
     WHERE UserId = p_userid;

    p_so_mon  := NVL(p_so_mon, 0);
    p_diem_tb := NVL(p_diem_tb, 0);
    p_diem_cao := NVL(p_diem_cao, 0);
    p_diem_thap := NVL(p_diem_thap, 0);
END P_THONG_KE_HOC_SINH;
/

CREATE OR REPLACE PROCEDURE P_XOA_DU_LIEU_CU (
    p_so_ngay_truoc IN NUMBER DEFAULT 365
)
IS
    v_ngay_cat TIMESTAMP;
BEGIN
    v_ngay_cat := SYSTIMESTAMP - NUMTODSINTERVAL(p_so_ngay_truoc, 'DAY');

    DELETE FROM KetQuaDuDoan
     WHERE NgayTinhToan < v_ngay_cat;

    DELETE FROM DanhGia
     WHERE NgayDanhGia < v_ngay_cat;
END P_XOA_DU_LIEU_CU;
/

-- ===== Procedures ported from database/procedures_sqlserver.sql =====

CREATE OR REPLACE PROCEDURE SP_REGISTER_STUDENT(
    p_username IN VARCHAR2,
    p_matkhau  IN VARCHAR2,
    p_hoten    IN VARCHAR2,
    p_email    IN VARCHAR2,
    p_loaiuser IN VARCHAR2 DEFAULT 'Student',
    p_newuserid OUT NUMBER
)
IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM UserThi WHERE UserName = p_username;
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20011, 'Username already exists');
    END IF;

    SELECT COUNT(*) INTO v_count FROM UserThi WHERE Email = p_email;
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20012, 'Email already exists');
    END IF;

    INSERT INTO UserThi (UserId, UserName, MatKhau, HoTen, Email, LoaiUser, NgayTao)
    VALUES (NULL, p_username, p_matkhau, p_hoten, p_email, p_loaiuser, SYSTIMESTAMP)
    RETURNING UserId INTO p_newuserid;
END SP_REGISTER_STUDENT;
/

CREATE OR REPLACE PROCEDURE SP_ADD_STUDENT_SCORE(
    p_userid IN NUMBER,
    p_monid  IN NUMBER,
    p_diemthi IN NUMBER,
    p_diemthuong IN NUMBER DEFAULT 0,
    p_diemid OUT NUMBER
)
IS
    v_exists NUMBER;
    v_heso NUMBER;
BEGIN
    IF p_diemthi < 0 OR p_diemthi > 10 THEN
        RAISE_APPLICATION_ERROR(-20013, 'Score must be between 0 and 10');
    END IF;

    SELECT COUNT(*) INTO v_exists FROM UserThi WHERE UserId = p_userid;
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20014, 'User does not exist');
    END IF;

    SELECT COUNT(*) INTO v_exists FROM MonTrongKhoiThi WHERE MonID = p_monid;
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20015, 'Subject does not exist');
    END IF;

    SELECT HeSo INTO v_heso FROM MonTrongKhoiThi WHERE MonID = p_monid;

    INSERT INTO Diem (DiemID, UserId, MonID, DiemThi, DiemThuong, HeSo, NgayNhap)
    VALUES (NULL, p_userid, p_monid, p_diemthi, p_diemthuong, v_heso, SYSTIMESTAMP)
    RETURNING DiemID INTO p_diemid;
END SP_ADD_STUDENT_SCORE;
/

CREATE OR REPLACE PROCEDURE SP_GET_STUDENT_RECOMMENDATIONS(
    p_userid IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN p_cursor FOR
        SELECT
            n.NganhID,
            n.TenNganh,
            n.MaNganh,
            t.TenTruong,
            t.MaTruong,
            n.DiemChuan,
            n.ChiTieuTuyen,
            MAX(d.DiemThi * d.HeSo) AS DiemCaoNhat,
            CASE
                WHEN MAX(d.DiemThi * d.HeSo) >= NVL(n.DiemChuan, 0) THEN 'DU_TIEU_CHI'
                ELSE 'CAN_CO_GANG'
            END AS TrangThaiTuyen,
            NVL(ROUND(AVG(dg.DiemDanhGia), 2), 0) AS DiemDanhGiaTrungBinh,
            MAX(dg.NhanXet) AS NhanXet
        FROM Nganh n
        JOIN TruongDH t ON n.TruongID = t.TruongID
        JOIN Diem d ON d.UserId = p_userid
        JOIN MonTrongKhoiThi m ON d.MonID = m.MonID
        JOIN KhoiThi k ON m.KhoiID = k.KhoiID
        LEFT JOIN DanhGia dg ON n.NganhID = dg.NganhID AND dg.UserId = p_userid
        WHERE k.TenKhoi = n.KhoiThi_YeuCau
        GROUP BY
            n.NganhID, n.TenNganh, n.MaNganh,
            t.TenTruong, t.MaTruong,
            n.DiemChuan, n.ChiTieuTuyen
        ORDER BY DiemCaoNhat DESC;
END SP_GET_STUDENT_RECOMMENDATIONS;
/

CREATE OR REPLACE PROCEDURE SP_UPDATE_MAJOR_INFO(
    p_nganhid IN NUMBER,
    p_tennganh IN VARCHAR2 DEFAULT NULL,
    p_diemchuan IN NUMBER DEFAULT NULL,
    p_chitieutuyen IN NUMBER DEFAULT NULL,
    p_mota IN VARCHAR2 DEFAULT NULL
)
IS
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM Nganh WHERE NganhID = p_nganhid;
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20016, 'Major does not exist');
    END IF;

    UPDATE Nganh
       SET TenNganh = COALESCE(p_tennganh, TenNganh),
           DiemChuan = COALESCE(p_diemchuan, DiemChuan),
           ChiTieuTuyen = COALESCE(p_chitieutuyen, ChiTieuTuyen),
           MoTa = COALESCE(p_mota, MoTa)
     WHERE NganhID = p_nganhid;
END SP_UPDATE_MAJOR_INFO;
/

CREATE OR REPLACE PROCEDURE SP_GET_UNIVERSITY_STATS(
    p_truongid IN NUMBER DEFAULT NULL,
    p_cursor OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN p_cursor FOR
        SELECT
            t.TruongID,
            t.TenTruong,
            t.MaTruong,
            t.DiaChi,
            COUNT(DISTINCT n.NganhID) AS SoNganh,
            ROUND(AVG(n.DiemChuan), 2) AS DiemChuanTrungBinh,
            SUM(n.ChiTieuTuyen) AS TongChiTieu,
            COUNT(DISTINCT dg.UserId) AS SoSinhVienDanhGia,
            NVL(ROUND(AVG(dg.DiemDanhGia), 2), 0) AS DiemDanhGiaTrungBinh
        FROM TruongDH t
        LEFT JOIN Nganh n ON t.TruongID = n.TruongID
        LEFT JOIN DanhGia dg ON n.NganhID = dg.NganhID
        WHERE p_truongid IS NULL OR t.TruongID = p_truongid
        GROUP BY t.TruongID, t.TenTruong, t.MaTruong, t.DiaChi
        ORDER BY t.TenTruong;
END SP_GET_UNIVERSITY_STATS;
/

PROMPT Procedures created.



PROMPT ===== Running 04_triggers.sql =====

-- StudyMatch (Oracle) - Triggers
-- Includes: auto-ID from sequences + validations + derived data refresh.

-- ===== Auto-ID triggers =====

CREATE OR REPLACE TRIGGER trg_userthi_bi
BEFORE INSERT ON UserThi
FOR EACH ROW
BEGIN
    IF :NEW.UserId IS NULL THEN
        :NEW.UserId := seq_userid.NEXTVAL;
    END IF;
    :NEW.NgayCapNhat := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_khoithi_bi
BEFORE INSERT ON KhoiThi
FOR EACH ROW
BEGIN
    IF :NEW.KhoiID IS NULL THEN
        :NEW.KhoiID := seq_khoiid.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_montrongkhoi_bi
BEFORE INSERT ON MonTrongKhoiThi
FOR EACH ROW
BEGIN
    IF :NEW.MonID IS NULL THEN
        :NEW.MonID := seq_monid.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_monhoc_bi
BEFORE INSERT ON MonHoc
FOR EACH ROW
BEGIN
    IF :NEW.MonHocID IS NULL THEN
        :NEW.MonHocID := seq_monhocid.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_truongdh_bi
BEFORE INSERT ON TruongDH
FOR EACH ROW
BEGIN
    IF :NEW.TruongID IS NULL THEN
        :NEW.TruongID := seq_truongid.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_nganh_bi
BEFORE INSERT ON Nganh
FOR EACH ROW
BEGIN
    IF :NEW.NganhID IS NULL THEN
        :NEW.NganhID := seq_nganhid.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_giaovien_bi
BEFORE INSERT ON GiaoVien
FOR EACH ROW
BEGIN
    IF :NEW.GiaoVienID IS NULL THEN
        :NEW.GiaoVienID := seq_giaovienid.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_ttts_bi
BEFORE INSERT ON ThongTinTuyenSinh
FOR EACH ROW
BEGIN
    IF :NEW.ThongTinID IS NULL THEN
        :NEW.ThongTinID := seq_ttuyenid.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_danhgia_bi
BEFORE INSERT ON DanhGia
FOR EACH ROW
BEGIN
    IF :NEW.DanhGiaID IS NULL THEN
        :NEW.DanhGiaID := seq_danhgiaid.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_hinhanhgv_bi
BEFORE INSERT ON HinhAnhGiaoVien
FOR EACH ROW
BEGIN
    IF :NEW.HinhAnhID IS NULL THEN
        :NEW.HinhAnhID := seq_hinhanhid.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_ketqua_bi
BEFORE INSERT ON KetQuaDuDoan
FOR EACH ROW
BEGIN
    IF :NEW.KetQuaID IS NULL THEN
        :NEW.KetQuaID := seq_ketquaid.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_lichsu_bi
BEFORE INSERT ON Lich_Su_Diem
FOR EACH ROW
BEGIN
    IF :NEW.LichSuID IS NULL THEN
        :NEW.LichSuID := seq_lichsuid.NEXTVAL;
    END IF;
END;
/

-- ===== Validation triggers =====

CREATE OR REPLACE TRIGGER trg_diem_validate
BEFORE INSERT OR UPDATE ON Diem
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.DiemID IS NULL THEN
        :NEW.DiemID := seq_diemid.NEXTVAL;
    END IF;

    IF NOT F_KT_DIEM_HOP_LE(:NEW.DiemThi) THEN
        RAISE_APPLICATION_ERROR(-20001, 'DiemThi must be between 0 and 10');
    END IF;

    IF :NEW.DiemThuong IS NULL THEN
        :NEW.DiemThuong := 0;
    END IF;

    IF :NEW.DiemThuong < 0 OR :NEW.DiemThuong > 1 THEN
        RAISE_APPLICATION_ERROR(-20002, 'DiemThuong must be between 0 and 1');
    END IF;

    IF :NEW.NgayNhap IS NOT NULL AND :NEW.NgayNhap > SYSTIMESTAMP THEN
        RAISE_APPLICATION_ERROR(-20003, 'Cannot add score with future date');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_danhgia_validate
BEFORE INSERT OR UPDATE ON DanhGia
FOR EACH ROW
BEGIN
    IF :NEW.DiemDanhGia < 1 OR :NEW.DiemDanhGia > 5 THEN
        RAISE_APPLICATION_ERROR(-20004, 'DiemDanhGia must be between 1 and 5');
    END IF;

    IF :NEW.NhanXet IS NOT NULL AND LENGTH(:NEW.NhanXet) > 500 THEN
        RAISE_APPLICATION_ERROR(-20005, 'NhanXet must be <= 500 chars');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_nganh_update_ngaysua
BEFORE UPDATE ON Nganh
FOR EACH ROW
BEGIN
    :NEW.NgaySua := SYSTIMESTAMP;
END;
/

-- ===== Audit/history trigger =====

CREATE OR REPLACE TRIGGER trg_diem_history
AFTER UPDATE OF DiemThi ON Diem
FOR EACH ROW
BEGIN
    INSERT INTO Lich_Su_Diem (LichSuID, DiemID, UserId, DiemCu, DiemMoi, NgayThayDoi)
    VALUES (NULL, :NEW.DiemID, :NEW.UserId, :OLD.DiemThi, :NEW.DiemThi, SYSTIMESTAMP);
END;
/

-- ===== Refresh KetQuaDuDoan without mutating-table error =====
-- Uses a COMPOUND TRIGGER so the refresh runs AFTER STATEMENT.

CREATE OR REPLACE TRIGGER trg_diem_refresh_ketqua
FOR INSERT OR UPDATE OR DELETE ON Diem
COMPOUND TRIGGER
    TYPE t_user_map IS TABLE OF BOOLEAN INDEX BY VARCHAR2(40);
    g_users t_user_map;

    PROCEDURE add_user(p_userid NUMBER) IS
    BEGIN
        IF p_userid IS NOT NULL THEN
            g_users(TO_CHAR(TRUNC(p_userid))) := TRUE;
        END IF;
    END;

AFTER EACH ROW IS
BEGIN
    IF INSERTING OR UPDATING THEN
        add_user(:NEW.UserId);
    END IF;
    IF DELETING THEN
        add_user(:OLD.UserId);
    END IF;
END AFTER EACH ROW;

AFTER STATEMENT IS
    v_key VARCHAR2(40);
BEGIN
    v_key := g_users.FIRST;
    WHILE v_key IS NOT NULL LOOP
        P_CAP_NHAT_KET_QUA(TO_NUMBER(v_key));
        v_key := g_users.NEXT(v_key);
    END LOOP;
END AFTER STATEMENT;
END trg_diem_refresh_ketqua;
/

PROMPT Triggers created.



PROMPT ===== Running 05_views.sql =====

-- StudyMatch (Oracle) - Views

-- Views based on database/views.sql

CREATE OR REPLACE VIEW V_DIEM_TRUNG_BINH AS
SELECT
    u.UserId,
    u.HoTen,
    u.Email,
    COUNT(d.DiemID) AS SoMonThi,
    ROUND(AVG(d.DiemThi), 2) AS DiemTrungBinh,
    MAX(d.DiemThi) AS DiemCaoNhat,
    MIN(d.DiemThi) AS DiemThapNhat
FROM UserThi u
LEFT JOIN Diem d ON u.UserId = d.UserId
GROUP BY u.UserId, u.HoTen, u.Email;


CREATE OR REPLACE VIEW V_NGANH_PHU_HOP AS
SELECT
    n.NganhID,
    n.TenNganh,
    t.TenTruong,
    n.DiemChuan,
    n.KhoiThi_YeuCau,
    n.ChiTieuTuyen,
    ROUND((n.DiemChuan * 0.85), 2) AS DiemToiThieu,
    ROUND((n.DiemChuan * 1.05), 2) AS DiemToiDa,
    COUNT(DISTINCT dg.DanhGiaID) AS SoDanhGia,
    ROUND(AVG(dg.DiemDanhGia), 2) AS DiemDanhGiaTrungBinh
FROM Nganh n
LEFT JOIN TruongDH t ON n.TruongID = t.TruongID
LEFT JOIN DanhGia dg ON n.NganhID = dg.NganhID
GROUP BY n.NganhID, n.TenNganh, t.TenTruong, n.DiemChuan, n.KhoiThi_YeuCau, n.ChiTieuTuyen;


CREATE OR REPLACE VIEW V_TUYEN_SINH_THEO_NAM AS
SELECT
    tts.NamTuyen,
    n.TenNganh,
    t.TenTruong,
    tts.TenHinhThuc,
    tts.DiemChuan,
    tts.DuToanChiTieu,
    ROW_NUMBER() OVER (PARTITION BY tts.NamTuyen ORDER BY tts.DiemChuan DESC) AS XepHang
FROM ThongTinTuyenSinh tts
JOIN Nganh n ON tts.NganhID = n.NganhID
JOIN TruongDH t ON n.TruongID = t.TruongID;


CREATE OR REPLACE VIEW V_GIAO_VIEN_INFO AS
SELECT
    gv.GiaoVienID,
    gv.TenGiaoVien,
    gv.MonDay,
    gv.Email,
    gv.SoDienThoai,
    COUNT(DISTINCT ha.HinhAnhID) AS SoHinhAnh,
    COUNT(DISTINCT tts.ThongTinID) AS SoLanDayKhoa
FROM GiaoVien gv
LEFT JOIN HinhAnhGiaoVien ha ON gv.GiaoVienID = ha.GiaoVienID
LEFT JOIN ThongTinTuyenSinh tts ON gv.GiaoVienID = tts.GiaoVienID
GROUP BY gv.GiaoVienID, gv.TenGiaoVien, gv.MonDay, gv.Email, gv.SoDienThoai;


CREATE OR REPLACE VIEW V_KET_QUA_CHI_TIET AS
SELECT
    kq.KetQuaID,
    u.HoTen,
    n.TenNganh,
    t.TenTruong,
    kq.DiemTrungBinh,
    kq.TiLePhuHop,
    n.DiemChuan,
    CASE
        WHEN kq.TiLePhuHop >= 90 THEN 'Rất Phù Hợp'
        WHEN kq.TiLePhuHop >= 80 THEN 'Phù Hợp'
        WHEN kq.TiLePhuHop >= 70 THEN 'Khá Phù Hợp'
        WHEN kq.TiLePhuHop >= 60 THEN 'Bình Thường'
        ELSE 'Ít Phù Hợp'
    END AS MucDoDanhGia,
    kq.NgayTinhToan
FROM KetQuaDuDoan kq
JOIN UserThi u ON kq.UserId = u.UserId
JOIN Nganh n ON kq.NganhID = n.NganhID
JOIN TruongDH t ON n.TruongID = t.TruongID;


-- Extra views similar to SQL Server versions (ported)

CREATE OR REPLACE VIEW VW_STUDENT_SCORES_SUMMARY AS
SELECT
    u.UserId,
    u.UserName,
    u.HoTen,
    u.Email,
    k.TenKhoi,
    m.TenMon,
    d.DiemThi,
    d.DiemThuong,
    CAST((d.DiemThi * d.HeSo + d.DiemThuong) AS NUMBER(5,2)) AS DiemTongCong,
    d.NgayNhap,
    ROW_NUMBER() OVER (PARTITION BY u.UserId, k.KhoiID ORDER BY d.NgayNhap DESC) AS DiemHeThong
FROM UserThi u
JOIN Diem d ON u.UserId = d.UserId
JOIN MonTrongKhoiThi m ON d.MonID = m.MonID
JOIN KhoiThi k ON m.KhoiID = k.KhoiID;


CREATE OR REPLACE VIEW VW_UNIVERSITY_MAJOR_INFO AS
SELECT
    n.NganhID,
    n.TenNganh,
    n.MaNganh,
    t.TenTruong,
    t.MaTruong,
    t.DiaChi,
    t.Website,
    n.DiemChuan,
    n.ChiTieuTuyen,
    n.KhoiThi_YeuCau,
    COUNT(DISTINCT dg.DanhGiaID) AS SoLuongDanhGia,
    NVL(ROUND(AVG(dg.DiemDanhGia), 2), 0) AS DiemTrungBinh
FROM Nganh n
JOIN TruongDH t ON n.TruongID = t.TruongID
LEFT JOIN DanhGia dg ON n.NganhID = dg.NganhID
GROUP BY
    n.NganhID, n.TenNganh, n.MaNganh,
    t.TenTruong, t.MaTruong, t.DiaChi, t.Website,
    n.DiemChuan, n.ChiTieuTuyen, n.KhoiThi_YeuCau;


CREATE OR REPLACE VIEW VW_STUDENT_RECOMMENDED_MAJORS AS
SELECT
    u.UserId,
    u.UserName,
    u.HoTen,
    n.NganhID,
    n.TenNganh,
    t.TenTruong,
    n.DiemChuan,
    MAX(d.DiemThi * d.HeSo) AS DiemCaoNhat,
    CASE
        WHEN MAX(d.DiemThi * d.HeSo) >= NVL(n.DiemChuan, 0) THEN 'Du tieu chi'
        ELSE 'Can co gang them'
    END AS TrangThaiTuyen
FROM UserThi u
JOIN Diem d ON u.UserId = d.UserId
JOIN MonTrongKhoiThi m ON d.MonID = m.MonID
JOIN KhoiThi k ON m.KhoiID = k.KhoiID
JOIN Nganh n ON k.TenKhoi = n.KhoiThi_YeuCau
JOIN TruongDH t ON n.TruongID = t.TruongID
GROUP BY
    u.UserId, u.UserName, u.HoTen,
    n.NganhID, n.TenNganh,
    t.TenTruong,
    n.DiemChuan;


CREATE OR REPLACE VIEW VW_TEACHER_ASSIGNMENTS AS
SELECT
    gv.GiaoVienID,
    gv.TenGiaoVien,
    gv.MonDay,
    gv.Email,
    gv.SoDienThoai,
    COUNT(DISTINCT ti.ThongTinID) AS SoNganhPhuTrach,
    (
      SELECT LISTAGG(x.TenNganh, ', ') WITHIN GROUP (ORDER BY x.TenNganh)
      FROM (
        SELECT DISTINCT n2.TenNganh
        FROM ThongTinTuyenSinh ti2
        JOIN Nganh n2 ON ti2.NganhID = n2.NganhID
        WHERE ti2.GiaoVienID = gv.GiaoVienID
      ) x
    ) AS DanhSachNganh
FROM GiaoVien gv
LEFT JOIN ThongTinTuyenSinh ti ON gv.GiaoVienID = ti.GiaoVienID
GROUP BY gv.GiaoVienID, gv.TenGiaoVien, gv.MonDay, gv.Email, gv.SoDienThoai;


CREATE OR REPLACE VIEW VW_ADMISSION_STATISTICS AS
SELECT
    t.TenTruong,
    COUNT(DISTINCT n.NganhID) AS SoNganh,
    ROUND(AVG(n.DiemChuan), 2) AS DiemChuanTrungBinh,
    SUM(n.ChiTieuTuyen) AS TongChiTieu,
    COUNT(DISTINCT dg.UserId) AS SoSinhVienDanhGia,
    MAX(dg.DiemDanhGia) AS DanhGiaMax,
    MIN(dg.DiemDanhGia) AS DanhGiaMin
FROM TruongDH t
LEFT JOIN Nganh n ON t.TruongID = n.TruongID
LEFT JOIN DanhGia dg ON n.NganhID = dg.NganhID
GROUP BY t.TruongID, t.TenTruong;


PROMPT Views created.



PROMPT ===== Running 06_sample_data.sql =====

-- StudyMatch (Oracle) - Sample data
-- Notes:
-- - No GO
-- - Use SYSTIMESTAMP
-- - MonTrongKhoiThi.MaMon must be unique => use suffix _A/_B/_C/_D

-- ===== KhoiThi =====
INSERT INTO KhoiThi (KhoiID, TenKhoi, MoTa) VALUES (NULL, 'A', 'Khối A - Toán, Lý, Hóa');
INSERT INTO KhoiThi (KhoiID, TenKhoi, MoTa) VALUES (NULL, 'B', 'Khối B - Toán, Hóa, Sinh');
INSERT INTO KhoiThi (KhoiID, TenKhoi, MoTa) VALUES (NULL, 'C', 'Khối C - Toán, Địa, Sử');
INSERT INTO KhoiThi (KhoiID, TenKhoi, MoTa) VALUES (NULL, 'D', 'Khối D - Ngữ Văn, Tiếng Anh, Lịch Sử');

-- ===== MonTrongKhoiThi =====
INSERT INTO MonTrongKhoiThi (MonID, KhoiID, TenMon, MaMon, HeSo)
VALUES (NULL, (SELECT KhoiID FROM KhoiThi WHERE TenKhoi='A'), 'Toán', 'TOAN_A', 1.0);
INSERT INTO MonTrongKhoiThi (MonID, KhoiID, TenMon, MaMon, HeSo)
VALUES (NULL, (SELECT KhoiID FROM KhoiThi WHERE TenKhoi='A'), 'Vật Lý', 'LY_A', 1.0);
INSERT INTO MonTrongKhoiThi (MonID, KhoiID, TenMon, MaMon, HeSo)
VALUES (NULL, (SELECT KhoiID FROM KhoiThi WHERE TenKhoi='A'), 'Hóa Học', 'HOA_A', 1.0);

INSERT INTO MonTrongKhoiThi (MonID, KhoiID, TenMon, MaMon, HeSo)
VALUES (NULL, (SELECT KhoiID FROM KhoiThi WHERE TenKhoi='B'), 'Toán', 'TOAN_B', 1.0);
INSERT INTO MonTrongKhoiThi (MonID, KhoiID, TenMon, MaMon, HeSo)
VALUES (NULL, (SELECT KhoiID FROM KhoiThi WHERE TenKhoi='B'), 'Hóa Học', 'HOA_B', 1.0);
INSERT INTO MonTrongKhoiThi (MonID, KhoiID, TenMon, MaMon, HeSo)
VALUES (NULL, (SELECT KhoiID FROM KhoiThi WHERE TenKhoi='B'), 'Sinh Học', 'SINH_B', 1.0);

INSERT INTO MonTrongKhoiThi (MonID, KhoiID, TenMon, MaMon, HeSo)
VALUES (NULL, (SELECT KhoiID FROM KhoiThi WHERE TenKhoi='C'), 'Toán', 'TOAN_C', 1.0);
INSERT INTO MonTrongKhoiThi (MonID, KhoiID, TenMon, MaMon, HeSo)
VALUES (NULL, (SELECT KhoiID FROM KhoiThi WHERE TenKhoi='C'), 'Địa Lý', 'DIA_C', 1.0);
INSERT INTO MonTrongKhoiThi (MonID, KhoiID, TenMon, MaMon, HeSo)
VALUES (NULL, (SELECT KhoiID FROM KhoiThi WHERE TenKhoi='C'), 'Lịch Sử', 'SU_C', 1.0);

INSERT INTO MonTrongKhoiThi (MonID, KhoiID, TenMon, MaMon, HeSo)
VALUES (NULL, (SELECT KhoiID FROM KhoiThi WHERE TenKhoi='D'), 'Ngữ Văn', 'VAN_D', 1.0);
INSERT INTO MonTrongKhoiThi (MonID, KhoiID, TenMon, MaMon, HeSo)
VALUES (NULL, (SELECT KhoiID FROM KhoiThi WHERE TenKhoi='D'), 'Tiáº¿ng Anh', 'ANH_D', 1.0);
INSERT INTO MonTrongKhoiThi (MonID, KhoiID, TenMon, MaMon, HeSo)
VALUES (NULL, (SELECT KhoiID FROM KhoiThi WHERE TenKhoi='D'), 'Lịch Sử', 'SU_D', 1.0);

-- ===== MonHoc =====
INSERT INTO MonHoc (MonHocID, TenMonHoc, MaMonHoc, MoTa) VALUES (NULL, 'Toán Học', 'TOAN', 'Môn Toán - Tư duy logic và tính toán');
INSERT INTO MonHoc (MonHocID, TenMonHoc, MaMonHoc, MoTa) VALUES (NULL, 'Vật Lý', 'LY', 'Môn Vật Lý - Khám phá hiện tượng tự nhiên');
INSERT INTO MonHoc (MonHocID, TenMonHoc, MaMonHoc, MoTa) VALUES (NULL, 'Hóa Học', 'HOA', 'Môn Hóa - Khoa học về phản ứng hóa học');
INSERT INTO MonHoc (MonHocID, TenMonHoc, MaMonHoc, MoTa) VALUES (NULL, 'Sinh Học', 'SINH', 'Môn Sinh - Khoa học sự sống');
INSERT INTO MonHoc (MonHocID, TenMonHoc, MaMonHoc, MoTa) VALUES (NULL, 'Địa Lý', 'DIA', 'Môn Địa - Học về không gian địa lý');
INSERT INTO MonHoc (MonHocID, TenMonHoc, MaMonHoc, MoTa) VALUES (NULL, 'Lịch Sử', 'SU', 'Môn Sử - Học lịch sử và các sự kiện');
INSERT INTO MonHoc (MonHocID, TenMonHoc, MaMonHoc, MoTa) VALUES (NULL, 'Ngữ Văn', 'VAN', 'Môn Văn - Học văn chương và tiếng Việt');
INSERT INTO MonHoc (MonHocID, TenMonHoc, MaMonHoc, MoTa) VALUES (NULL, 'Tiếng Anh', 'ANH', 'Môn Anh - Ngôn ngữ quốc tế');
INSERT INTO MonHoc (MonHocID, TenMonHoc, MaMonHoc, MoTa) VALUES (NULL, 'Tin Học', 'TINHOC', 'Môn Tin - Lập trình và khoa học máy tính');
INSERT INTO MonHoc (MonHocID, TenMonHoc, MaMonHoc, MoTa) VALUES (NULL, 'Thể Dục', 'THEDUC', 'Môn Thể Dục - Rèn luyện sức khoẻ');

-- ===== TruongDH =====
INSERT INTO TruongDH (TruongID, TenTruong, MaTruong, Website, DiaChi, SoDienThoai, Email)
VALUES (NULL, 'Đại học Bách Khoa Hà Nội', 'HUST', 'https://hust.edu.vn', '1 Đại Cồ Việt, Hai Bà Trưng, Hà Nội', '0243869000', 'info@hust.edu.vn');
INSERT INTO TruongDH (TruongID, TenTruong, MaTruong, Website, DiaChi, SoDienThoai, Email)
VALUES (NULL, 'Đại học Quốc gia Hà Nội', 'VNU', 'https://vnu.edu.vn', '144 Xuân Thuỷ, Cầu Giấy, Hà Nội', '0243754000', 'info@vnu.edu.vn');
INSERT INTO TruongDH (TruongID, TenTruong, MaTruong, Website, DiaChi, SoDienThoai, Email)
VALUES (NULL, 'Đại học Kinh Tế Quốc Dân', 'NEU', 'https://neu.edu.vn', '207 Giải Phóng, Hà Nội', '0243551100', 'info@neu.edu.vn');
INSERT INTO TruongDH (TruongID, TenTruong, MaTruong, Website, DiaChi, SoDienThoai, Email)
VALUES (NULL, 'Đại học Sư Phạm Hà Nội', 'HNUE', 'https://hnue.edu.vn', '136 Xuân Thuy, Hà Nội', '0243755180', 'info@hnue.edu.vn');
INSERT INTO TruongDH (TruongID, TenTruong, MaTruong, Website, DiaChi, SoDienThoai, Email)
VALUES (NULL, 'Đại học Công Nghiệp Hà Nội', 'HAUI', 'https://haui.edu.vn', '298 Cầu Diễn, Hà Nội', '0243636558', 'info@haui.edu.vn');

-- ===== Nganh =====
INSERT INTO Nganh (NganhID, TruongID, TenNganh, MaNganh, MoTa, ChiTieuTuyen, DiemChuan, KhoiThi_YeuCau)
VALUES (NULL, (SELECT TruongID FROM TruongDH WHERE MaTruong='HUST'), 'Kỹ Thuật Máy', 'KTMT', 'Chuyên ngành về cơ khí và máy móc', 150, 24.0, 'A');
INSERT INTO Nganh (NganhID, TruongID, TenNganh, MaNganh, MoTa, ChiTieuTuyen, DiemChuan, KhoiThi_YeuCau)
VALUES (NULL, (SELECT TruongID FROM TruongDH WHERE MaTruong='HUST'), 'Công Nghệ Thông Tin', 'CNTT', 'Lập trình, phân tích hệ thống', 200, 25.5, 'A');
INSERT INTO Nganh (NganhID, TruongID, TenNganh, MaNganh, MoTa, ChiTieuTuyen, DiemChuan, KhoiThi_YeuCau)
VALUES (NULL, (SELECT TruongID FROM TruongDH WHERE MaTruong='HUST'), 'Điện - Điện Tử', 'DDET', 'Kỹ thuật điện và điện tử', 100, 23.5, 'A');
INSERT INTO Nganh (NganhID, TruongID, TenNganh, MaNganh, MoTa, ChiTieuTuyen, DiemChuan, KhoiThi_YeuCau)
VALUES (NULL, (SELECT TruongID FROM TruongDH WHERE MaTruong='VNU'), 'Quản Lý Kinh Tế', 'QLKT', 'Quản lý và điều hành doanh nghiệp', 250, 22.0, 'B');
INSERT INTO Nganh (NganhID, TruongID, TenNganh, MaNganh, MoTa, ChiTieuTuyen, DiemChuan, KhoiThi_YeuCau)
VALUES (NULL, (SELECT TruongID FROM TruongDH WHERE MaTruong='VNU'), 'Luật Quốc Tế', 'LQTE', 'Chuyên gia về luật quốc tế', 80, 23.0, 'C');
INSERT INTO Nganh (NganhID, TruongID, TenNganh, MaNganh, MoTa, ChiTieuTuyen, DiemChuan, KhoiThi_YeuCau)
VALUES (NULL, (SELECT TruongID FROM TruongDH WHERE MaTruong='NEU'), 'Kế Toán', 'KT', 'Quản lý tài chính và kế toán', 300, 21.0, 'B');
INSERT INTO Nganh (NganhID, TruongID, TenNganh, MaNganh, MoTa, ChiTieuTuyen, DiemChuan, KhoiThi_YeuCau)
VALUES (NULL, (SELECT TruongID FROM TruongDH WHERE MaTruong='NEU'), 'Kinh Tế Lượng', 'KTL', 'Phân tích kinh tế bằng toán học', 100, 23.5, 'A');
INSERT INTO Nganh (NganhID, TruongID, TenNganh, MaNganh, MoTa, ChiTieuTuyen, DiemChuan, KhoiThi_YeuCau)
VALUES (NULL, (SELECT TruongID FROM TruongDH WHERE MaTruong='HNUE'), 'Sư Phạm Toán', 'SPTN', 'Đào tạo giáo viên Toán', 200, 22.5, 'A');
INSERT INTO Nganh (NganhID, TruongID, TenNganh, MaNganh, MoTa, ChiTieuTuyen, DiemChuan, KhoiThi_YeuCau)
VALUES (NULL, (SELECT TruongID FROM TruongDH WHERE MaTruong='HNUE'), 'Sư Phạm Tiếng Anh', 'SPTA', 'Đào tạo giáo viên Tiếng Anh', 180, 20.0, 'D');
INSERT INTO Nganh (NganhID, TruongID, TenNganh, MaNganh, MoTa, ChiTieuTuyen, DiemChuan, KhoiThi_YeuCau)
VALUES (NULL, (SELECT TruongID FROM TruongDH WHERE MaTruong='HAUI'), 'Kỹ Thuật Xây Dựng', 'KTXD', 'Thiết kế và thi công công trình', 120, 23.0, 'A');

-- ===== UserThi =====
INSERT INTO UserThi (UserId, UserName, MatKhau, HoTen, Email, LoaiUser, NgayTao)
VALUES (NULL, 'student001', 'hashed_password_1', 'Nguyễn Văn A', 'vana@student.edu.vn', 'Student', SYSTIMESTAMP);
INSERT INTO UserThi (UserId, UserName, MatKhau, HoTen, Email, LoaiUser, NgayTao)
VALUES (NULL, 'student002', 'hashed_password_2', 'Trần Thị B', 'thib@student.edu.vn', 'Student', SYSTIMESTAMP);
INSERT INTO UserThi (UserId, UserName, MatKhau, HoTen, Email, LoaiUser, NgayTao)
VALUES (NULL, 'student003', 'hashed_password_3', 'Lê Minh C', 'minhc@student.edu.vn', 'Student', SYSTIMESTAMP);
INSERT INTO UserThi (UserId, UserName, MatKhau, HoTen, Email, LoaiUser, NgayTao)
VALUES (NULL, 'student004', 'hashed_password_4', 'Pháº¡m Thu D', 'thud@student.edu.vn', 'Student', SYSTIMESTAMP);
INSERT INTO UserThi (UserId, UserName, MatKhau, HoTen, Email, LoaiUser, NgayTao)
VALUES (NULL, 'student005', 'hashed_password_5', 'Hoàng Quốc E', 'quoce@student.edu.vn', 'Student', SYSTIMESTAMP);

-- ===== Diem =====
INSERT INTO Diem (DiemID, UserId, MonID, DiemThi, DiemThuong, HeSo, NgayNhap)
VALUES (NULL, (SELECT UserId FROM UserThi WHERE UserName='student001'), (SELECT MonID FROM MonTrongKhoiThi WHERE MaMon='TOAN_A'), 8.5, 0.5, 1.0, SYSTIMESTAMP);
INSERT INTO Diem (DiemID, UserId, MonID, DiemThi, DiemThuong, HeSo, NgayNhap)
VALUES (NULL, (SELECT UserId FROM UserThi WHERE UserName='student001'), (SELECT MonID FROM MonTrongKhoiThi WHERE MaMon='LY_A'), 7.8, 0.3, 1.0, SYSTIMESTAMP);
INSERT INTO Diem (DiemID, UserId, MonID, DiemThi, DiemThuong, HeSo, NgayNhap)
VALUES (NULL, (SELECT UserId FROM UserThi WHERE UserName='student001'), (SELECT MonID FROM MonTrongKhoiThi WHERE MaMon='HOA_A'), 8.2, 0.4, 1.0, SYSTIMESTAMP);

INSERT INTO Diem (DiemID, UserId, MonID, DiemThi, DiemThuong, HeSo, NgayNhap)
VALUES (NULL, (SELECT UserId FROM UserThi WHERE UserName='student002'), (SELECT MonID FROM MonTrongKhoiThi WHERE MaMon='TOAN_B'), 9.0, 0.5, 1.0, SYSTIMESTAMP);
INSERT INTO Diem (DiemID, UserId, MonID, DiemThi, DiemThuong, HeSo, NgayNhap)
VALUES (NULL, (SELECT UserId FROM UserThi WHERE UserName='student002'), (SELECT MonID FROM MonTrongKhoiThi WHERE MaMon='HOA_B'), 8.5, 0.4, 1.0, SYSTIMESTAMP);
INSERT INTO Diem (DiemID, UserId, MonID, DiemThi, DiemThuong, HeSo, NgayNhap)
VALUES (NULL, (SELECT UserId FROM UserThi WHERE UserName='student002'), (SELECT MonID FROM MonTrongKhoiThi WHERE MaMon='SINH_B'), 7.9, 0.3, 1.0, SYSTIMESTAMP);

INSERT INTO Diem (DiemID, UserId, MonID, DiemThi, DiemThuong, HeSo, NgayNhap)
VALUES (NULL, (SELECT UserId FROM UserThi WHERE UserName='student003'), (SELECT MonID FROM MonTrongKhoiThi WHERE MaMon='TOAN_C'), 7.5, 0.3, 1.0, SYSTIMESTAMP);
INSERT INTO Diem (DiemID, UserId, MonID, DiemThi, DiemThuong, HeSo, NgayNhap)
VALUES (NULL, (SELECT UserId FROM UserThi WHERE UserName='student003'), (SELECT MonID FROM MonTrongKhoiThi WHERE MaMon='DIA_C'), 8.1, 0.4, 1.0, SYSTIMESTAMP);
INSERT INTO Diem (DiemID, UserId, MonID, DiemThi, DiemThuong, HeSo, NgayNhap)
VALUES (NULL, (SELECT UserId FROM UserThi WHERE UserName='student003'), (SELECT MonID FROM MonTrongKhoiThi WHERE MaMon='SU_C'), 7.8, 0.3, 1.0, SYSTIMESTAMP);

INSERT INTO Diem (DiemID, UserId, MonID, DiemThi, DiemThuong, HeSo, NgayNhap)
VALUES (NULL, (SELECT UserId FROM UserThi WHERE UserName='student004'), (SELECT MonID FROM MonTrongKhoiThi WHERE MaMon='VAN_D'), 8.8, 0.5, 1.0, SYSTIMESTAMP);
INSERT INTO Diem (DiemID, UserId, MonID, DiemThi, DiemThuong, HeSo, NgayNhap)
VALUES (NULL, (SELECT UserId FROM UserThi WHERE UserName='student004'), (SELECT MonID FROM MonTrongKhoiThi WHERE MaMon='ANH_D'), 9.2, 0.5, 1.0, SYSTIMESTAMP);
INSERT INTO Diem (DiemID, UserId, MonID, DiemThi, DiemThuong, HeSo, NgayNhap)
VALUES (NULL, (SELECT UserId FROM UserThi WHERE UserName='student004'), (SELECT MonID FROM MonTrongKhoiThi WHERE MaMon='SU_D'), 8.5, 0.4, 1.0, SYSTIMESTAMP);

INSERT INTO Diem (DiemID, UserId, MonID, DiemThi, DiemThuong, HeSo, NgayNhap)
VALUES (NULL, (SELECT UserId FROM UserThi WHERE UserName='student005'), (SELECT MonID FROM MonTrongKhoiThi WHERE MaMon='TOAN_A'), 6.5, 0.2, 1.0, SYSTIMESTAMP);
INSERT INTO Diem (DiemID, UserId, MonID, DiemThi, DiemThuong, HeSo, NgayNhap)
VALUES (NULL, (SELECT UserId FROM UserThi WHERE UserName='student005'), (SELECT MonID FROM MonTrongKhoiThi WHERE MaMon='LY_A'), 7.2, 0.3, 1.0, SYSTIMESTAMP);
INSERT INTO Diem (DiemID, UserId, MonID, DiemThi, DiemThuong, HeSo, NgayNhap)
VALUES (NULL, (SELECT UserId FROM UserThi WHERE UserName='student005'), (SELECT MonID FROM MonTrongKhoiThi WHERE MaMon='HOA_A'), 6.8, 0.2, 1.0, SYSTIMESTAMP);

-- ===== GiaoVien =====
INSERT INTO GiaoVien (GiaoVienID, TenGiaoVien, MonDay, Email, SoDienThoai, ChuyenMon)
VALUES (NULL, 'Thầy Phạm Quân', 'Toán', 'quan.pham@hust.edu.vn', '0912345678', 'Đại Số, Giải Tích');
INSERT INTO GiaoVien (GiaoVienID, TenGiaoVien, MonDay, Email, SoDienThoai, ChuyenMon)
VALUES (NULL, 'Cô Hoàng Hoa', 'Vật Lý', 'hoa.hoang@hust.edu.vn', '0912345679', 'Cơ Học, Điện Từ');
INSERT INTO GiaoVien (GiaoVienID, TenGiaoVien, MonDay, Email, SoDienThoai, ChuyenMon)
VALUES (NULL, 'Thầy Trần Long', 'Hóa Học', 'long.tran@hust.edu.vn', '0912345680', 'Hóa Hữu Cơ, Vô Cơ');
INSERT INTO GiaoVien (GiaoVienID, TenGiaoVien, MonDay, Email, SoDienThoai, ChuyenMon)
VALUES (NULL, 'Cô Lý Huân', 'Sinh Học', 'huan.ly@hnue.edu.vn', '0912345681', 'Tế Bào, Di Truyền');
INSERT INTO GiaoVien (GiaoVienID, TenGiaoVien, MonDay, Email, SoDienThoai, ChuyenMon)
VALUES (NULL, 'Thầy Bùi Minh', 'Tiếng Anh', 'minh.bui@hnue.edu.vn', '0912345682', 'Văn Phạm Anh, Phát Âm');

-- ===== ThongTinTuyenSinh =====
INSERT INTO ThongTinTuyenSinh (ThongTinID, NganhID, GiaoVienID, TenHinhThuc, NamTuyen, DiemChuan, DuToanChiTieu)
VALUES (NULL,
        (SELECT NganhID FROM Nganh WHERE MaNganh='KTMT'),
        (SELECT GiaoVienID FROM GiaoVien WHERE TenGiaoVien='Thầy Phạm Quân'),
        'Xét tuyển đại học', 2024, 24.0, 150);

INSERT INTO ThongTinTuyenSinh (ThongTinID, NganhID, GiaoVienID, TenHinhThuc, NamTuyen, DiemChuan, DuToanChiTieu)
VALUES (NULL,
        (SELECT NganhID FROM Nganh WHERE MaNganh='CNTT'),
        (SELECT GiaoVienID FROM GiaoVien WHERE TenGiaoVien='Thầy Phạm Quân'),
        'Xét tuyển đại học', 2024, 25.5, 200);

INSERT INTO ThongTinTuyenSinh (ThongTinID, NganhID, GiaoVienID, TenHinhThuc, NamTuyen, DiemChuan, DuToanChiTieu)
VALUES (NULL,
        (SELECT NganhID FROM Nganh WHERE MaNganh='KT'),
        (SELECT GiaoVienID FROM GiaoVien WHERE TenGiaoVien='Tháº§y Tráº§n Long'),
        'Xét tuyển đại học', 2024, 21.0, 300);

INSERT INTO ThongTinTuyenSinh (ThongTinID, NganhID, GiaoVienID, TenHinhThuc, NamTuyen, DiemChuan, DuToanChiTieu)
VALUES (NULL,
        (SELECT NganhID FROM Nganh WHERE MaNganh='SPTA'),
        (SELECT GiaoVienID FROM GiaoVien WHERE TenGiaoVien='Thầy Bùi Minh'),
        'Xét tuyển đại học', 2024, 20.0, 180);

INSERT INTO ThongTinTuyenSinh (ThongTinID, NganhID, GiaoVienID, TenHinhThuc, NamTuyen, DiemChuan, DuToanChiTieu)
VALUES (NULL,
        (SELECT NganhID FROM Nganh WHERE MaNganh='KTXD'),
        (SELECT GiaoVienID FROM GiaoVien WHERE TenGiaoVien='Cô Hoàng Hoa'),
        'Xét tuyển đại học', 2024, 23.0, 120);

-- ===== DanhGia =====
INSERT INTO DanhGia (DanhGiaID, NganhID, UserId, DiemDanhGia, NhanXet, NgayDanhGia)
VALUES (NULL, (SELECT NganhID FROM Nganh WHERE MaNganh='KTMT'), (SELECT UserId FROM UserThi WHERE UserName='student001'), 4, 'Ngành rất tuyệt vời, cơ sở vật chất tốt', SYSTIMESTAMP);
INSERT INTO DanhGia (DanhGiaID, NganhID, UserId, DiemDanhGia, NhanXet, NgayDanhGia)
VALUES (NULL, (SELECT NganhID FROM Nganh WHERE MaNganh='CNTT'), (SELECT UserId FROM UserThi WHERE UserName='student001'), 5, 'Giảng dạy chất lượng, học được nhiều điều bổ ích', SYSTIMESTAMP);
INSERT INTO DanhGia (DanhGiaID, NganhID, UserId, DiemDanhGia, NhanXet, NgayDanhGia)
VALUES (NULL, (SELECT NganhID FROM Nganh WHERE MaNganh='DDET'), (SELECT UserId FROM UserThi WHERE UserName='student002'), 4, 'Nội dung hay, đòi hỏi sự tập trung cao', SYSTIMESTAMP);
INSERT INTO DanhGia (DanhGiaID, NganhID, UserId, DiemDanhGia, NhanXet, NgayDanhGia)
VALUES (NULL, (SELECT NganhID FROM Nganh WHERE MaNganh='KT'), (SELECT UserId FROM UserThi WHERE UserName='student003'), 5, 'Giáo viên tâm huyết, hỗ trợ sinh viên tốt', SYSTIMESTAMP);
INSERT INTO DanhGia (DanhGiaID, NganhID, UserId, DiemDanhGia, NhanXet, NgayDanhGia)
VALUES (NULL, (SELECT NganhID FROM Nganh WHERE MaNganh='SPTA'), (SELECT UserId FROM UserThi WHERE UserName='student004'), 4, 'Khóa học bổ ích, kỹ năng thực tiễn tốt', SYSTIMESTAMP);
INSERT INTO DanhGia (DanhGiaID, NganhID, UserId, DiemDanhGia, NhanXet, NgayDanhGia)
VALUES (NULL, (SELECT NganhID FROM Nganh WHERE MaNganh='QLKT'), (SELECT UserId FROM UserThi WHERE UserName='student005'), 3, 'Nội dung có phần nặng, cần học tập chăm chỉ', SYSTIMESTAMP);

COMMIT;

PROMPT Sample data inserted.



PROMPT ===== All done =====

